#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Summarize per-frame visual-hazard component distributions by case and workflow phase.

This script is exploratory. It does not define final clinical cutoffs. It creates
candidate distribution summaries and distribution-based candidate thresholds for
later visual, surgeon-rating, and clinical-outcome validation.

Inputs should generally be local per-frame metric CSVs generated by
05_compute_frame_visual_hazard_components.py. Outputs may contain case IDs and
local paths, so write them under reports/ and do not commit them to GitHub.
"""

from __future__ import annotations

import argparse
import json
import math
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_METRICS_DIR = PROJECT_ROOT / "data" / "derived" / "quality_metrics" / "per_frame"
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "reports" / "phase_component_distributions"
SUMMARY_CSV_NAME = "_frame_score_summary.csv"


@dataclass(frozen=True)
class ComponentSpec:
    component: str
    score_col: str
    tier: str
    interpretation: str


DEFAULT_COMPONENT_SPECS: List[ComponentSpec] = [
    ComponentSpec(
        "structural_visibility_loss",
        "structural_visibility_loss_v1",
        "tier1_main",
        "Loss of local structural information; not a pure blur metric.",
    ),
    ComponentSpec(
        "center_low_structure_area",
        "center_low_structure_area_v1",
        "tier1_main",
        "Center-weighted low-structure area; useful as central-field structural-loss descriptor.",
    ),
    ComponentSpec(
        "whiteout",
        "whiteout_ratio_v1",
        "tier1_main_photometric",
        "Near-white / overexposure pixel ratio; photometric hazard descriptor.",
    ),
    ComponentSpec(
        "low_light_or_blackout",
        "low_light_or_blackout_ratio_v1",
        "tier1_main_photometric",
        "Very-low-value pixel ratio; low-light / blackout photometric hazard descriptor.",
    ),
    ComponentSpec(
        "reblur_response_loss",
        "reblur_response_loss_v1",
        "tier2_auxiliary",
        "Weak response to additional Gaussian reblur; low high-frequency / low-texture proxy.",
    ),
    ComponentSpec(
        "veil_low_contrast",
        "veil_low_contrast_score_v1",
        "tier2_auxiliary",
        "Low-contrast + low-edge descriptor; not validated smoke/fog.",
    ),
    ComponentSpec(
        "raw_blackness",
        "blackness_raw_ratio_v1",
        "tier2_auxiliary",
        "Raw dark-pixel ratio; generic blackness descriptor, not anthracosis.",
    ),
    ComponentSpec(
        "corrected_blackness",
        "blackness_corrected_ratio_v1",
        "tier2_auxiliary",
        "Illumination-corrected dark-pixel ratio; generic blackness descriptor, not anthracosis.",
    ),
    ComponentSpec(
        "specular_like_reflection",
        "specular_like_ratio_v1",
        "tier3_reconsider",
        "High-value low-saturation pixels; currently overlaps with whiteout and needs redesign.",
    ),
]

LEGACY_BADNESS_SPEC = ComponentSpec(
    "legacy_badness_alias",
    "composite_degradation_score",
    "legacy_screening_index",
    "Legacy badness-like screening index. In the current scaffold this is an alias of structural_visibility_loss_v1/focus_badness_v1, not an independently validated composite.",
)

VALIDITY_FLAG_COLUMNS = [
    "near_uniform_frame_candidate_v1",
    "large_whiteout_candidate_v1",
    "large_blackout_candidate_v1",
    "color_bar_or_test_pattern_candidate_v1",
    "photometric_failure_candidate_v1",
    "image_validity_problem_candidate_v1",
    "component_review_valid_candidate_v1",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Summarize visual-hazard component distributions by case and workflow phase."
    )
    parser.add_argument(
        "--metrics-dir",
        type=Path,
        default=DEFAULT_METRICS_DIR,
        help=f"Directory containing per-case metric CSVs. Default: {DEFAULT_METRICS_DIR}",
    )
    parser.add_argument(
        "--annotation-root",
        type=Path,
        default=None,
        help=(
            "Optional SurgCap video/annotation directory containing CASE###_annotation*.json. "
            "If provided, workflow Level-1/Level-2 labels are assigned by interval overlap."
        ),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Output directory for summary CSVs. Default: {DEFAULT_OUTPUT_DIR}",
    )
    parser.add_argument(
        "--case",
        nargs="*",
        default=None,
        help="Optional case_id filters, e.g. --case CASE003 CASE010",
    )
    parser.add_argument(
        "--component-col",
        nargs="*",
        default=None,
        help="Optional score columns. Defaults to the curated Phase 2B component set.",
    )
    parser.add_argument(
        "--include-legacy-badness",
        action="store_true",
        help="Also summarize composite_degradation_score as legacy_badness_alias if present.",
    )
    parser.add_argument(
        "--threshold-quantiles",
        nargs="*",
        type=float,
        default=[0.90, 0.95, 0.99],
        help="Candidate threshold quantiles. Default: 0.90 0.95 0.99",
    )
    parser.add_argument(
        "--phase-level",
        nargs="*",
        default=["Level-1", "Level-2"],
        choices=["Level-0", "Level-1", "Level-2"],
        help="Workflow annotation levels to summarize. Default: Level-1 Level-2",
    )
    parser.add_argument(
        "--time-col",
        default="sample_time_sec",
        help="Frame timestamp column. Default: sample_time_sec",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Load and summarize to stdout without writing CSVs.",
    )
    return parser.parse_args()


def infer_case_id_from_path(path: Path) -> str:
    stem = path.stem
    for suffix in ["_frame_scores", "_metrics", "_visual_hazard_components"]:
        if stem.endswith(suffix):
            stem = stem[: -len(suffix)]
    return stem


def list_metric_csvs(metrics_dir: Path, case_filter: Optional[set[str]]) -> List[Path]:
    paths = sorted(p for p in metrics_dir.glob("*.csv") if p.name != SUMMARY_CSV_NAME)
    if case_filter:
        return [p for p in paths if infer_case_id_from_path(p) in case_filter]
    return paths


def load_metric_frames(metrics_dir: Path, case_filter: Optional[set[str]]) -> pd.DataFrame:
    paths = list_metric_csvs(metrics_dir, case_filter)
    if not paths:
        raise FileNotFoundError(f"No metric CSVs found in {metrics_dir}")
    dfs = []
    for path in paths:
        df = pd.read_csv(path)
        if "case_id" not in df.columns:
            df["case_id"] = infer_case_id_from_path(path)
        else:
            df["case_id"] = df["case_id"].fillna(infer_case_id_from_path(path)).astype(str)
        df["source_metric_csv"] = str(path)
        dfs.append(df)
    out = pd.concat(dfs, ignore_index=True, sort=False)
    if "metric_status" in out.columns:
        out = out[(out["metric_status"].isna()) | (out["metric_status"].astype(str) == "ok")].copy()
    return out


def version_key(path: Path) -> Tuple[int, str]:
    name = path.name
    m = re.search(r"_v(\d+)\.json$", name)
    if m:
        return (int(m.group(1)), name)
    return (1, name)


def find_annotation_json(annotation_root: Path, case_id: str) -> Optional[Path]:
    candidates = sorted(annotation_root.glob(f"{case_id}_annotation*.json"), key=version_key)
    candidates = [p for p in candidates if "backup" not in p.name.lower()]
    if not candidates:
        # Some cases may be under nested folders, e.g. residual/excluded folders.
        candidates = sorted(annotation_root.rglob(f"{case_id}_annotation*.json"), key=version_key)
        candidates = [p for p in candidates if "backup" not in p.name.lower()]
    return candidates[-1] if candidates else None


def load_surgcap_segments(annotation_path: Path) -> List[dict]:
    obj = json.loads(annotation_path.read_text(encoding="utf-8"))
    segments = obj.get("active_annotation", {}).get("segments", [])
    cleaned = []
    for s in segments:
        try:
            start = float(s.get("start_sec"))
            end = float(s.get("end_sec"))
        except Exception:
            continue
        if not math.isfinite(start) or not math.isfinite(end) or end < start:
            continue
        cleaned.append(
            {
                "level": str(s.get("level", "")),
                "label": str(s.get("label", "")),
                "start_sec": start,
                "end_sec": end,
            }
        )
    return cleaned


def assign_workflow_labels(df: pd.DataFrame, annotation_root: Optional[Path], time_col: str) -> pd.DataFrame:
    df = df.copy()
    for level in ["Level-0", "Level-1", "Level-2"]:
        df[f"workflow_{level.lower().replace('-', '')}_label"] = ""

    if annotation_root is None:
        return df
    if time_col not in df.columns:
        print(f"[WARN] time column '{time_col}' not found; workflow labels will be blank.")
        return df

    for case_id, idx in df.groupby("case_id").groups.items():
        ann = find_annotation_json(annotation_root, str(case_id))
        if ann is None:
            print(f"[WARN] no annotation JSON found for {case_id}")
            continue
        try:
            segments = load_surgcap_segments(ann)
        except Exception as exc:
            print(f"[WARN] failed to read annotation for {case_id}: {ann} ({exc})")
            continue
        t = pd.to_numeric(df.loc[idx, time_col], errors="coerce")
        for s in segments:
            col = f"workflow_{s['level'].lower().replace('-', '')}_label"
            if col not in df.columns:
                continue
            mask = (t >= s["start_sec"]) & (t <= s["end_sec"])
            if mask.any():
                df.loc[t.index[mask], col] = s["label"]
        print(f"[INFO] assigned workflow labels for {case_id}: {ann.name}")
    return df


def component_specs_from_args(component_cols: Optional[Sequence[str]], include_legacy: bool) -> List[ComponentSpec]:
    if component_cols:
        builtins = {s.score_col: s for s in DEFAULT_COMPONENT_SPECS}
        specs = [builtins.get(c, ComponentSpec(c.replace("_v1", ""), c, "custom", "Custom score column.")) for c in component_cols]
    else:
        specs = list(DEFAULT_COMPONENT_SPECS)
    if include_legacy:
        specs.append(LEGACY_BADNESS_SPEC)
    return specs


def sample_interval_by_case(df: pd.DataFrame, time_col: str) -> Dict[str, float]:
    out: Dict[str, float] = {}
    if time_col not in df.columns:
        return {str(c): 1.0 for c in df["case_id"].unique()}
    for case_id, g in df.groupby("case_id"):
        t = pd.to_numeric(g[time_col], errors="coerce").dropna().sort_values().to_numpy()
        if len(t) >= 2:
            diffs = np.diff(t)
            diffs = diffs[np.isfinite(diffs) & (diffs > 0)]
            out[str(case_id)] = float(np.median(diffs)) if len(diffs) else 1.0
        else:
            out[str(case_id)] = 1.0
    return out


def q_name(q: float) -> str:
    pct = int(round(q * 1000))
    if pct % 10 == 0:
        return f"p{pct // 10}"
    return f"p{pct / 10:g}".replace(".", "p")


def numeric_series(df: pd.DataFrame, col: str) -> pd.Series:
    return pd.to_numeric(df[col], errors="coerce")


def describe_scores(values: pd.Series, quantiles: Sequence[float]) -> Dict[str, float]:
    x = pd.to_numeric(values, errors="coerce").dropna()
    out: Dict[str, float] = {
        "n_nonmissing": int(len(x)),
        "mean": float(x.mean()) if len(x) else np.nan,
        "sd": float(x.std(ddof=1)) if len(x) > 1 else np.nan,
        "min": float(x.min()) if len(x) else np.nan,
        "max": float(x.max()) if len(x) else np.nan,
        "zero_fraction": float((x <= 0).mean()) if len(x) else np.nan,
        "nonzero_fraction": float((x > 0).mean()) if len(x) else np.nan,
    }
    for q in quantiles:
        out[q_name(q)] = float(x.quantile(q)) if len(x) else np.nan
    return out


def max_consecutive_seconds(t: pd.Series, above: pd.Series, sample_interval: float) -> float:
    # Use count-based duration. This is robust to 1 fps sparse review-derived data.
    flags = above.fillna(False).astype(bool).to_numpy()
    best = 0
    current = 0
    for flag in flags:
        if flag:
            current += 1
            best = max(best, current)
        else:
            current = 0
    return float(best * sample_interval)


def build_global_cutoffs(df: pd.DataFrame, specs: Sequence[ComponentSpec], quantiles: Sequence[float]) -> pd.DataFrame:
    rows = []
    for spec in specs:
        if spec.score_col not in df.columns:
            continue
        x = numeric_series(df, spec.score_col).dropna()
        for q in quantiles:
            rows.append(
                {
                    "component": spec.component,
                    "score_col": spec.score_col,
                    "tier": spec.tier,
                    "threshold_scope": "global",
                    "phase_level": "",
                    "phase_label": "",
                    "quantile": q,
                    "quantile_name": q_name(q),
                    "threshold_value": float(x.quantile(q)) if len(x) else np.nan,
                    "n_frames": int(len(x)),
                    "interpretation": spec.interpretation,
                }
            )
    return pd.DataFrame(rows)


def build_phase_cutoffs(df: pd.DataFrame, specs: Sequence[ComponentSpec], quantiles: Sequence[float], phase_levels: Sequence[str]) -> pd.DataFrame:
    rows = []
    for phase_level in phase_levels:
        label_col = f"workflow_{phase_level.lower().replace('-', '')}_label"
        if label_col not in df.columns:
            continue
        phase_labels = df[label_col].replace("", "NoLabel").fillna("NoLabel")
        tmp = df.copy()
        tmp["_phase_label"] = phase_labels
        for phase_label, g in tmp.groupby("_phase_label", dropna=False):
            for spec in specs:
                if spec.score_col not in g.columns:
                    continue
                x = numeric_series(g, spec.score_col).dropna()
                for q in quantiles:
                    rows.append(
                        {
                            "component": spec.component,
                            "score_col": spec.score_col,
                            "tier": spec.tier,
                            "threshold_scope": "phase_specific",
                            "phase_level": phase_level,
                            "phase_label": phase_label,
                            "quantile": q,
                            "quantile_name": q_name(q),
                            "threshold_value": float(x.quantile(q)) if len(x) else np.nan,
                            "n_frames": int(len(x)),
                            "interpretation": spec.interpretation,
                        }
                    )
    return pd.DataFrame(rows)


def summarize_case_component(
    df: pd.DataFrame,
    specs: Sequence[ComponentSpec],
    quantiles: Sequence[float],
    global_thresholds: pd.DataFrame,
    time_col: str,
    interval_map: Dict[str, float],
) -> pd.DataFrame:
    threshold_lookup = {
        (r["score_col"], r["quantile_name"]): r["threshold_value"]
        for _, r in global_thresholds.iterrows()
        if r["threshold_scope"] == "global"
    }
    rows = []
    for case_id, g in df.groupby("case_id"):
        dt = interval_map.get(str(case_id), 1.0)
        for spec in specs:
            if spec.score_col not in g.columns:
                continue
            x = numeric_series(g, spec.score_col)
            row = {
                "case_id": case_id,
                "component": spec.component,
                "score_col": spec.score_col,
                "tier": spec.tier,
                "n_frames": int(len(g)),
                "estimated_duration_sec": float(len(g) * dt),
                "score_time_integral": float(np.nansum(x.to_numpy(dtype=float)) * dt),
                "sample_interval_sec": dt,
                "interpretation": spec.interpretation,
            }
            row.update(describe_scores(x, quantiles))
            for q in quantiles:
                name = q_name(q)
                thr = threshold_lookup.get((spec.score_col, name), np.nan)
                above = x >= thr if np.isfinite(thr) else pd.Series(False, index=g.index)
                row[f"global_{name}_threshold"] = float(thr) if np.isfinite(thr) else np.nan
                row[f"frac_ge_global_{name}"] = float(above.mean()) if len(above) else np.nan
                row[f"seconds_ge_global_{name}"] = float(above.sum() * dt)
                row[f"max_consecutive_seconds_ge_global_{name}"] = max_consecutive_seconds(g.get(time_col, pd.Series(index=g.index)), above, dt)
            rows.append(row)
    return pd.DataFrame(rows)


def summarize_case_phase_component(
    df: pd.DataFrame,
    specs: Sequence[ComponentSpec],
    quantiles: Sequence[float],
    global_thresholds: pd.DataFrame,
    phase_levels: Sequence[str],
    time_col: str,
    interval_map: Dict[str, float],
) -> pd.DataFrame:
    threshold_lookup = {
        (r["score_col"], r["quantile_name"]): r["threshold_value"]
        for _, r in global_thresholds.iterrows()
        if r["threshold_scope"] == "global"
    }
    rows = []
    for phase_level in phase_levels:
        label_col = f"workflow_{phase_level.lower().replace('-', '')}_label"
        if label_col not in df.columns:
            continue
        tmp = df.copy()
        tmp["_phase_label"] = tmp[label_col].replace("", "NoLabel").fillna("NoLabel")
        for (case_id, phase_label), g in tmp.groupby(["case_id", "_phase_label"], dropna=False):
            dt = interval_map.get(str(case_id), 1.0)
            for spec in specs:
                if spec.score_col not in g.columns:
                    continue
                x = numeric_series(g, spec.score_col)
                row = {
                    "case_id": case_id,
                    "phase_level": phase_level,
                    "phase_label": phase_label,
                    "component": spec.component,
                    "score_col": spec.score_col,
                    "tier": spec.tier,
                    "n_frames": int(len(g)),
                    "estimated_duration_sec": float(len(g) * dt),
                    "score_time_integral": float(np.nansum(x.to_numpy(dtype=float)) * dt),
                    "sample_interval_sec": dt,
                    "interpretation": spec.interpretation,
                }
                row.update(describe_scores(x, quantiles))
                for q in quantiles:
                    name = q_name(q)
                    thr = threshold_lookup.get((spec.score_col, name), np.nan)
                    above = x >= thr if np.isfinite(thr) else pd.Series(False, index=g.index)
                    row[f"global_{name}_threshold"] = float(thr) if np.isfinite(thr) else np.nan
                    row[f"frac_ge_global_{name}"] = float(above.mean()) if len(above) else np.nan
                    row[f"seconds_ge_global_{name}"] = float(above.sum() * dt)
                    row[f"max_consecutive_seconds_ge_global_{name}"] = max_consecutive_seconds(g.get(time_col, pd.Series(index=g.index)), above, dt)
                rows.append(row)
    return pd.DataFrame(rows)


def summarize_validity_flags(df: pd.DataFrame, phase_levels: Sequence[str]) -> pd.DataFrame:
    cols = [c for c in VALIDITY_FLAG_COLUMNS if c in df.columns]
    if not cols:
        return pd.DataFrame()
    rows = []
    groupings: List[Tuple[str, List[str]]] = [("case", ["case_id"])]
    for phase_level in phase_levels:
        label_col = f"workflow_{phase_level.lower().replace('-', '')}_label"
        if label_col in df.columns:
            groupings.append((f"case_{phase_level}", ["case_id", label_col]))
    for scope, keys in groupings:
        tmp = df.copy()
        for k in keys:
            tmp[k] = tmp[k].replace("", "NoLabel").fillna("NoLabel")
        for values, g in tmp.groupby(keys, dropna=False):
            if not isinstance(values, tuple):
                values = (values,)
            base = {"scope": scope, "n_frames": int(len(g))}
            for k, v in zip(keys, values):
                base[k] = v
            for col in cols:
                s = pd.to_numeric(g[col], errors="coerce").fillna(0.0) >= 0.5
                base[f"{col}_count"] = int(s.sum())
                base[f"{col}_fraction"] = float(s.mean()) if len(s) else np.nan
            rows.append(base)
    return pd.DataFrame(rows)


def write_csv(df: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)
    print(f"[OK] wrote {path} rows={len(df)}")


def main() -> None:
    args = parse_args()
    case_filter = set(args.case) if args.case else None
    specs = component_specs_from_args(args.component_col, args.include_legacy_badness)

    df = load_metric_frames(args.metrics_dir, case_filter)
    missing = [s.score_col for s in specs if s.score_col not in df.columns]
    if missing:
        print("[WARN] missing score columns skipped:", ", ".join(missing))
        specs = [s for s in specs if s.score_col in df.columns]
    if not specs:
        raise ValueError("No requested component score columns are present in metric CSVs.")

    df = assign_workflow_labels(df, args.annotation_root, args.time_col)
    interval_map = sample_interval_by_case(df, args.time_col)

    global_cutoffs = build_global_cutoffs(df, specs, args.threshold_quantiles)
    phase_cutoffs = build_phase_cutoffs(df, specs, args.threshold_quantiles, args.phase_level)
    case_summary = summarize_case_component(df, specs, args.threshold_quantiles, global_cutoffs, args.time_col, interval_map)
    case_phase_summary = summarize_case_phase_component(
        df, specs, args.threshold_quantiles, global_cutoffs, args.phase_level, args.time_col, interval_map
    )
    validity_summary = summarize_validity_flags(df, args.phase_level)

    score_cols = [s.score_col for s in specs if s.score_col in df.columns]
    corr = df[score_cols].apply(pd.to_numeric, errors="coerce").corr(method="spearman")
    corr.index.name = "score_col"

    component_metadata = pd.DataFrame([s.__dict__ for s in specs])

    print(f"Loaded frames: {len(df)}")
    print(f"Cases: {df['case_id'].nunique()}")
    print("Components:", ", ".join(s.component for s in specs))
    print("Threshold quantiles:", ", ".join(q_name(q) for q in args.threshold_quantiles))
    if args.include_legacy_badness:
        print("[NOTE] legacy badness is summarized as a screening alias, not as a validated composite.")

    if args.dry_run:
        print(case_summary.head(20).to_string(index=False))
        return

    out = args.output_dir
    write_csv(component_metadata, out / "component_metric_metadata.csv")
    write_csv(global_cutoffs, out / "global_component_candidate_cutoffs.csv")
    write_csv(phase_cutoffs, out / "phase_component_candidate_cutoffs.csv")
    write_csv(case_summary, out / "case_component_distribution_summary.csv")
    write_csv(case_phase_summary, out / "case_phase_component_distribution_summary.csv")
    if not validity_summary.empty:
        write_csv(validity_summary, out / "image_validity_flag_summary.csv")
    corr.to_csv(out / "component_spearman_correlation.csv")
    print(f"[OK] wrote {out / 'component_spearman_correlation.csv'} rows={len(corr)}")


if __name__ == "__main__":
    main()
